# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'coinmanager' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for coinmanager

  target 'coinmanager-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'coinmanagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'coinmanager-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for coinmanager-tvOS

  target 'coinmanager-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
